layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

# github: [metadata]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: rodydavisjr
  linkedin: rodydavis
  stackoverflow: 7303311
  twitter: rodydavis
  youtube: nodamagefound

topics:
  - name: Flutter
  - name: iOS
  - name: Android
  - name: REST API
  - name: CI/CD

  # - name: Flutter
  #   web_url: https://github.com/topics/flutter
  #   image_url: /assets/images/flutter/logo.jpg
