name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 'v1.10.6'
          channel: 'master'
      - run: flutter pub get
      - run: flutter build web
      - run: firebase deploy --token "$FIREBASE_TOKEN"
